// This file is auto-generated by the Supabase CLI
// Run `supabase gen types typescript` to regenerate
// Do not edit this file manually
/* eslint-disable @typescript-eslint/no-empty-object-type */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
	public: {
		Tables: {
			// Types will be populated after running migrations
		};
		Views: {
			[_ in never]: never;
		};
		Functions: {
			[_ in never]: never;
		};
		Enums: {
			[_ in never]: never;
		};
		CompositeTypes: {
			[_ in never]: never;
		};
	};
}
